/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import conexion.Conexion;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jehud
 */
public class GestionUsuariosForm extends javax.swing.JFrame {

    /**
     * Creates new form GestionUsuariosForm
     */
    
    // Variable para almacenar el ID del usuario seleccionado
    private int idSeleccionado = 0;
    
    
    public GestionUsuariosForm() {
        initComponents();
        
        //ComboBox Rol.
        cboRol.removeAllItems();
        cboRol.addItem("Administrador");
        cboRol.addItem("Profesor");
        cboRol.addItem("Alumno");
    
        //ComboBox Estado
        cboEstado.removeAllItems();
        cboEstado.addItem("Activo");
        cboEstado.addItem("Inactivo");
    
        //Llama al metodo para cargar la tabla.
        cargarTabla();
    }
        
    // Método para cargar usuarios en la tabla.
    private void cargarTabla() {
        // Definir columnas de la tabla.
        String[] columnas = {"ID", "Usuario", "Contraseña", "Rol", "Estado", "Fecha Creación"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        Conexion conexion = new Conexion();

        try {
            ResultSet rs = conexion.ejecutarConsulta("SELECT * FROM usuarios ORDER BY id");

            while (rs.next()) {
                Object[] fila = {
                    rs.getInt("id"),
                    rs.getString("usuario"),
                    "******", // Ocultar contraseña
                    rs.getString("rol"),
                    rs.getString("estado"),
                    rs.getString("fecha_creacion")
                };
                modelo.addRow(fila);
            }

            tblUsuarios.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al cargar usuarios: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        } finally {
            conexion.cerrarConexion();
        }
    }
    
    // Método para limpiar los campos del formulario.
    private void limpiarCampos() {
        txtUsuario.setText("");
        txtPassword.setText("");
        cboRol.setSelectedIndex(0);
        cboEstado.setSelectedIndex(0);
        idSeleccionado = 0;
        txtUsuario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        cboRol = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRestablecerPass = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("GESTIÓN DE USUARIOS");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña:");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Rol:");

        cboRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Estado:");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRestablecerPass.setText("Restablecer Contraseña");
        btnRestablecerPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerPassActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsuario)
                    .addComponent(txtPassword)
                    .addComponent(cboRol, 0, 139, Short.MAX_VALUE)
                    .addComponent(cboEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRestablecerPass)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(cboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnRestablecerPass)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        // TODO add your handling code here:
        int fila = tblUsuarios.getSelectedRow();
    
        if (fila >= 0) {
            // Cargar datos de la fila a los campos.
            idSeleccionado = Integer.parseInt(tblUsuarios.getValueAt(fila, 0).toString());
            txtUsuario.setText(tblUsuarios.getValueAt(fila, 1).toString());
            
            // La contraseña no se muestra (por seguridad).
            txtPassword.setText("");
            cboRol.setSelectedItem(tblUsuarios.getValueAt(fila, 3).toString());
            cboEstado.setSelectedItem(tblUsuarios.getValueAt(fila, 4).toString());
        }
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String usuario = txtUsuario.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();
        String rol = cboRol.getSelectedItem().toString();
        String estado = cboEstado.getSelectedItem().toString();
        
        // Validar que los campos no estén vacíos
        if (usuario.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
            "Por favor complete todos los campos",
            "Campos vacíos",
            JOptionPane.WARNING_MESSAGE);
            return;
        }
    
        Conexion conexion = new Conexion();
    
        try{
        // Verificar si el usuario ya existe
            ResultSet rs = conexion.ejecutarConsulta(
            "SELECT * FROM usuarios WHERE usuario = '" + usuario + "'"
            );
        
        if (rs.next()) {
            JOptionPane.showMessageDialog(this,
                "El usuario '" + usuario + "' ya existe",
                "Usuario duplicado",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //Agregar nuevo usuario.
        String sql = "INSERT INTO usuarios (usuario, contrasenia, rol, estado) " +
                     "VALUES ('" + usuario + "', '" + password + "', '" + rol + "', '" + estado + "')";
        
        boolean exito = conexion.ejecutarActualizacion(sql);
        
        if (exito) {
            JOptionPane.showMessageDialog(this,
                "Usuario agregado exitosamente",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
            
            cargarTabla(); //Recargar la tabla
            limpiarCampos(); //Limpiar los campos
        } else {
            JOptionPane.showMessageDialog(this,
                "Error al agregar el usuario",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        
    } 
    
        catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
        } 
        
        finally {
        conexion.cerrarConexion();
        }
      
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        
        // Verificar que haya un usuario seleccionado
        if (idSeleccionado == 0) {
            JOptionPane.showMessageDialog(this,
                "Por favor seleccione un usuario de la tabla",
                "No hay selección",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String usuario = txtUsuario.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();
        String rol = cboRol.getSelectedItem().toString();
        String estado = cboEstado.getSelectedItem().toString();
        
        // Validar que los campos no estén vacíos
        if (usuario.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "El campo usuario no puede estar vacío",
                "Campo vacío",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
    
        Conexion conexion = new Conexion();
        
        try {
        // Verificar si el nuevo nombre de usuario ya existe (en otro registro)
        ResultSet rs = conexion.ejecutarConsulta(
            "SELECT * FROM usuarios WHERE usuario = '" + usuario + "' AND id != " + idSeleccionado
        );
        
        if (rs.next()) {
            JOptionPane.showMessageDialog(this,
                "El usuario '" + usuario + "' ya existe",
                "Usuario duplicado",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
         //SQL de actualización
        String sql;
        
        // Si escribió una nueva contraseña actualizarla también.
        if (!password.isEmpty()) {
            sql = "UPDATE usuarios SET " +
                  "usuario = '" + usuario + "', " +
                  "contrasenia = '" + password + "', " +
                  "rol = '" + rol + "', " +
                  "estado = '" + estado + "' " +
                  "WHERE id = " + idSeleccionado;
        } else {
            // Si no escribió contraseña, no actualizarla.
            sql = "UPDATE usuarios SET " +
                  "usuario = '" + usuario + "', " +
                  "rol = '" + rol + "', " +
                  "estado = '" + estado + "' " +
                  "WHERE id = " + idSeleccionado;
        }
    
        boolean exito = conexion.ejecutarActualizacion(sql);
        
        if (exito) {
            JOptionPane.showMessageDialog(this,
                "Usuario actualizado exitosamente",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
            
            cargarTabla(); // Recargar la tabla
            limpiarCampos(); // Limpiar los campos
        } else {
            JOptionPane.showMessageDialog(this,
                "Error al actualizar el usuario",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        
    } 
        catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
        } 
        
        finally {
        conexion.cerrarConexion();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        // Verificar que haya un usuario seleccionado
        if (idSeleccionado == 0) {
            JOptionPane.showMessageDialog(this,
                "Por favor seleccione un usuario de la tabla",
                 "No hay selección",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Confirmación antes de eliminar
        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de eliminar este usuario?\nEsta acción no se puede deshacer.",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
    
        // Si el usuario cancela, salir
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
    }
    
        Conexion conexion = new Conexion();
        
        try {
        // Eliminar el usuario de la base de datos.,
        String sql = "DELETE FROM usuarios WHERE id = " + idSeleccionado;
        
        boolean exito = conexion.ejecutarActualizacion(sql);
        
        if (exito) {
            JOptionPane.showMessageDialog(this,
                "Usuario eliminado exitosamente",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
            
            cargarTabla(); // Recargar la tabla
            limpiarCampos(); // Limpiar los campos
        } else {
            JOptionPane.showMessageDialog(this,
                "Error al eliminar el usuario",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    } finally {
        conexion.cerrarConexion();
    }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRestablecerPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerPassActionPerformed
        // TODO add your handling code here:
        
        // Verificar que haya un usuario seleccionado
        if (idSeleccionado == 0) {
            JOptionPane.showMessageDialog(this,
                "Por favor seleccione un usuario de la tabla",
                "No hay selección",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Solicitar la nueva contraseña
        String nuevaPassword = JOptionPane.showInputDialog(this,
            "Ingrese la nueva contraseña:",
            "Restablecer contraseña",
            JOptionPane.PLAIN_MESSAGE);
    
        // Si se cancela o no se ingresa.
        if (nuevaPassword == null || nuevaPassword.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Operación cancelada",
                "Cancelado",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    
        nuevaPassword = nuevaPassword.trim();
    
        Conexion conexion = new Conexion();
        
        try {
        //Actualizar solo la contraseña
        String sql = "UPDATE usuarios SET contrasenia = '" + nuevaPassword + "' WHERE id = " + idSeleccionado;
        
        boolean exito = conexion.ejecutarActualizacion(sql);
        
        if (exito) {
            JOptionPane.showMessageDialog(this,
                "Contraseña restablecida exitosamente",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
            
            cargarTabla(); // Recargar la tabla
            limpiarCampos(); // Limpiar los campos
        } else {
            JOptionPane.showMessageDialog(this,
                "Error al restablecer la contraseña",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            }
        
        } 
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            } 
        
        finally {
            conexion.cerrarConexion();
        }
    }//GEN-LAST:event_btnRestablecerPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUsuariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionUsuariosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRestablecerPass;
    private javax.swing.JComboBox<String> cboEstado;
    private javax.swing.JComboBox<String> cboRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
